## Cifras derivadas de la simulacion v2 para el texto. Uso: Rscript cifras_v2.R (desde salidas/)
R <- read.csv("simulacion_v2_replicas.csv")
cat("vacia % por escenario:\n"); print(round(100 * tapply(R$nucleo_vacio, list(R$p, R$mecanismo), mean)))
cat("soluciones interior media:\n"); print(round(tapply(R$n_sol_interior, list(R$p, R$mecanismo), mean), 1))
cat("enumerada n:\n"); print(tapply(R$exterior_enumerada, list(R$p, R$mecanismo), sum))
cat("incompatibles:\n"); print(tapply(R$del_imposible, list(R$p, R$mecanismo), sum, na.rm = TRUE))
cat("full en interior %:\n"); print(round(100 * tapply(R$full_en_interior, list(R$p, R$mecanismo), mean)))
cat("cierta con falsos % rango:", range(round(100 * tapply(R$nucleo_falsos > 0, list(R$p, R$mecanismo), mean))), "\n")
cat("vacias:", sum(R$nucleo_vacio), " informativas:", sum(!R$nucleo_vacio), "\n")
s <- R[R$p >= 0.1, ]; cat("enumeradas p>=0.10:", tapply(s$exterior_enumerada, s$p, sum), "\n")
