## Compara replica a replica la simulacion v2 (codigo corregido) con la v1. Uso: Rscript comparar_v1_v2.R (desde salidas/)
fs <- list.files("sim_v2", pattern = "^t[0-9]+[.]csv$", full.names = TRUE)
L <- lapply(fs, read.csv, stringsAsFactors = FALSE); ok <- sapply(L, function(d) !"error" %in% names(d))
cols <- Reduce(intersect, lapply(L[ok], names)); n <- do.call(rbind, lapply(L[ok], function(d) d[, cols]))
o <- read.csv("simulacion_v1_replicas.csv"); m <- merge(n, o, by = c("p", "mecanismo", "rep"), suffixes = c(".n", ".o"))
cat("replicas comparadas:", nrow(m), " errores:", sum(!ok), "\n")
cat("fallos interior:", sum(m$int_sin_sol), " en", sum(m$int_sin_sol > 0), "replicas; exteriores invalidadas:", sum(m$ext_fallo), "\n")
cat("GARANTIA (cierta solo con terminos de la completa): nuevo", sum(m$nucleo_en_full.n), "/", nrow(m), " original", sum(m$nucleo_en_full.o), "\n")
cat("cierta con falsos que la completa no tiene:", sum(m$nucleo_falsos.n > 0 & m$full_falsos.n == 0), "\n")
cat("cierta vacia: nuevo", sum(m$nucleo_vacio.n), " original", sum(m$nucleo_vacio.o), "\n")
cat("incompatibles certificadas: nuevo", sum(m$del_imposible.n, na.rm = TRUE), "/", sum(m$exterior_enumerada.n), " original", sum(m$del_imposible.o, na.rm = TRUE), "/", sum(m$exterior_enumerada.o), "\n")
cat("datos identicos:", all(m$n_completos.n == m$n_completos.o), " eliminacion igual:", all(m$del_falsos.n == m$del_falsos.o), "\n")
